# Generated by Django 3.2.7 on 2021-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.DateTimeField(auto_created=True, auto_now_add=True, help_text='注册时间')),
                ('openid', models.CharField(db_index=True, help_text='用户的openid', max_length=255)),
                ('nickname', models.CharField(help_text='用户的昵称', max_length=32)),
                ('gender', models.CharField(help_text='性别', max_length=1)),
                ('status', models.BooleanField(default=True, help_text='用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='用户的id')),
                ('openid', models.CharField(db_index=True, help_text='用户的openid', max_length=255)),
                ('level', models.IntegerField(help_text='用户等级')),
                ('max_health_point', models.IntegerField(help_text='最大生命值')),
                ('health_point', models.IntegerField(help_text='当前生命值')),
                ('max_mana_point', models.IntegerField(help_text='最大法力值')),
                ('mana_point', models.IntegerField(help_text='当前法力值')),
                ('strength', models.IntegerField(default=5, help_text='力量')),
                ('dexterity', models.IntegerField(default=5, help_text='敏捷')),
                ('intelligence', models.IntegerField(default=5, help_text='智力')),
                ('vitality', models.IntegerField(default=5, help_text='体力')),
                ('armor', models.IntegerField(default=0, help_text='护甲')),
                ('lucky', models.IntegerField(default=1, help_text='幸运')),
                ('charm', models.IntegerField(default=3, help_text='魅力')),
                ('user_status', models.BooleanField(default=True, help_text='用户状态，用在用户注销的时候')),
            ],
        ),
    ]
