# Generated by Django 3.2.7 on 2021-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_remove_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='health_point',
            field=models.IntegerField(default=100, help_text='当前生命值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mana_point',
            field=models.IntegerField(default=100, help_text='当前法力值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_health_point',
            field=models.IntegerField(default=100, help_text='最大生命值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_mana_point',
            field=models.IntegerField(default=100, help_text='最大法力值'),
        ),
    ]
