# Generated by Django 3.2.7 on 2021-09-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(help_text='性别', max_length=10),
        ),
    ]
