# Generated by Django 3.2.7 on 2021-09-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(help_text='性别, 1:男，2:女', null=True),
        ),
    ]
