# Generated by Django 3.2.7 on 2021-09-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.BigIntegerField(default=0, help_text='当前修为'),
        ),
    ]
