# Generated by Django 3.2.7 on 2021-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_userprofile_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, help_text='等级')),
                ('level_label', models.CharField(help_text='等级展示', max_length=100)),
                ('consume_exp', models.BigIntegerField(default=0, help_text='消耗经验')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
