# Generated by Django 3.2.7 on 2021-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_levelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level_label',
            field=models.CharField(default='筑基一期', help_text='等级展示名称', max_length=100),
        ),
    ]
