# Generated by Django 3.2.7 on 2021-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_userprofile_level_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, help_text='等级')),
                ('level_label', models.CharField(help_text='等级展示', max_length=100)),
                ('consume_exp', models.BigIntegerField(default=0, help_text='消耗经验')),
                ('exp_level_limit', models.IntegerField(default=0, help_text='境界等级限制')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='levelconfig',
            name='body_level_limit',
            field=models.IntegerField(default=1, help_text='肉身等级需求'),
        ),
        migrations.AddField(
            model_name='levelconfig',
            name='exp_ampl',
            field=models.IntegerField(default=5, help_text='修为加成'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body_level',
            field=models.IntegerField(default=1, help_text='肉身'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body_level_label',
            field=models.CharField(default='铁骨一阶', help_text='身体等级展示名称', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exp_add',
            field=models.IntegerField(default=5, help_text='每秒修为增长数量'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, help_text='境界'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_label',
            field=models.CharField(default='筑基一阶', help_text='境界展示名称', max_length=100),
        ),
    ]
