# Generated by Django 3.2.7 on 2021-09-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_auto_20210922_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodylevelconfig',
            name='last_level',
            field=models.IntegerField(default=0, help_text='上一等级'),
        ),
        migrations.AddField(
            model_name='levelconfig',
            name='last_level',
            field=models.IntegerField(default=0, help_text='上一等级'),
        ),
    ]
