# Generated by Django 3.2.7 on 2021-10-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_auto_20210924_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodylevelconfig',
            options={'verbose_name': '肉身等级配置', 'verbose_name_plural': '肉身等级配置'},
        ),
        migrations.AlterModelOptions(
            name='levelconfig',
            options={'verbose_name': '修炼等级配置', 'verbose_name_plural': '修炼等级配置'},
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='consume_exp',
            field=models.BigIntegerField(default=0, verbose_name='消耗经验'),
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='exp_level_limit',
            field=models.IntegerField(default=0, verbose_name='境界等级限制'),
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='last_level',
            field=models.IntegerField(default=0, verbose_name='上一等级'),
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='level',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='level_label',
            field=models.CharField(max_length=100, verbose_name='等级展示'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='body_level_limit',
            field=models.IntegerField(default=1, verbose_name='肉身等级需求'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='consume_exp',
            field=models.BigIntegerField(default=0, verbose_name='消耗经验'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='exp_ampl',
            field=models.IntegerField(default=5, verbose_name='修为加成'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='last_level',
            field=models.IntegerField(default=0, verbose_name='上一等级'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='level',
            field=models.IntegerField(default=0, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='level_label',
            field=models.CharField(max_length=100, verbose_name='等级展示'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='性别, 1:男，2:女'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='用户的昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='用户的openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='armor',
            field=models.IntegerField(default=0, verbose_name='护甲'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_level',
            field=models.IntegerField(default=1, verbose_name='肉身'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_level_label',
            field=models.CharField(default='铁骨一阶', max_length=100, verbose_name='身体等级展示名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='charm',
            field=models.IntegerField(default=3, verbose_name='魅力'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dexterity',
            field=models.IntegerField(default=5, verbose_name='敏捷'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.BigIntegerField(default=0, verbose_name='当前修为'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_add',
            field=models.IntegerField(default=5, verbose_name='每秒修为增长数量'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_point',
            field=models.IntegerField(default=100, verbose_name='当前生命值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intelligence',
            field=models.IntegerField(default=5, verbose_name='智力'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='境界'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_label',
            field=models.CharField(default='筑基一阶', max_length=100, verbose_name='境界展示名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lucky',
            field=models.IntegerField(default=1, verbose_name='幸运'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mana_point',
            field=models.IntegerField(default=100, verbose_name='当前法力值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_health_point',
            field=models.IntegerField(default=100, verbose_name='最大生命值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_mana_point',
            field=models.IntegerField(default=100, verbose_name='最大法力值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='用户的openid'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strength',
            field=models.IntegerField(default=5, verbose_name='力量'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.user', verbose_name='用户的id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.BooleanField(default=True, verbose_name='用户状态，用在用户注销的时候'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vitality',
            field=models.IntegerField(default=5, verbose_name='体力'),
        ),
    ]
