# Generated by Django 3.2.7 on 2021-10-12 10:21

from django.db import migrations, models
import robot.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_auto_20211012_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gem',
            field=models.BigIntegerField(default=robot.models.user.random_gem, verbose_name='灵石'),
        ),
    ]
