# Generated by Django 3.2.7 on 2021-10-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_userprofile_gem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mana_point',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_mana_point',
        ),
    ]
