# Generated by Django 3.2.7 on 2021-10-13 09:12

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import robot.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_auto_20211013_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '玩家资料', 'verbose_name_plural': '玩家资料'},
        ),
        migrations.AddField(
            model_name='bodylevelconfig',
            name='consume_exp_range',
            field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(default=(1, 10), verbose_name='消耗经验的随机范围'),
        ),
        migrations.AddField(
            model_name='levelconfig',
            name='consume_exp_range',
            field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(default=(1, 10), verbose_name='消耗经验的随机范围'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_body_level_exp',
            field=models.BigIntegerField(default=robot.models.user.random_exp, verbose_name='肉身升级需要的修为'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_level_exp',
            field=models.BigIntegerField(default=robot.models.user.random_exp, verbose_name='升级需要的修为'),
        ),
    ]
