# Generated by Django 3.2.8 on 2021-10-26 04:00

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0017_auto_20211013_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodylevelconfig',
            name='consume_exp',
        ),
        migrations.RemoveField(
            model_name='levelconfig',
            name='consume_exp',
        ),
        migrations.AddField(
            model_name='bodylevelconfig',
            name='default_exam_probability',
            field=models.IntegerField(default=80, verbose_name='默认渡劫成功率'),
        ),
        migrations.AddField(
            model_name='bodylevelconfig',
            name='is_exam',
            field=models.BooleanField(default=True, verbose_name='是否需要渡劫'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attack',
            field=models.IntegerField(default=5, verbose_name='攻击力'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='defense',
            field=models.IntegerField(default=5, verbose_name='攻击力'),
        ),
        migrations.AlterField(
            model_name='bodylevelconfig',
            name='consume_exp_range',
            field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(default=[1, 10], verbose_name='消耗经验的随机范围'),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='consume_exp_range',
            field=django.contrib.postgres.fields.ranges.BigIntegerRangeField(default=[1, 10], verbose_name='消耗经验的随机范围'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_level_label',
            field=models.CharField(default='凡人之躯一阶', max_length=100, verbose_name='身体等级展示名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_label',
            field=models.CharField(default='练气一阶', max_length=100, verbose_name='境界展示名称'),
        ),
    ]
