# Generated by Django 3.2.8 on 2022-02-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_auto_20211026_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='consume_time',
            field=models.IntegerField(default=1, verbose_name='探索消耗的时间，单位（秒）'),
        ),
    ]
