# Generated by Django 3.2.8 on 2022-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_mapmodel_consume_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmodel',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
    ]
