# Generated by Django 3.2.8 on 2022-03-01 10:06

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0020_mapmodel_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapmonster',
            options={'verbose_name': '地图怪物配置', 'verbose_name_plural': '地图怪物配置'},
        ),
        migrations.AddField(
            model_name='mapmodel',
            name='level_limit',
            field=models.IntegerField(default=1, verbose_name='进入地图的等级限制'),
        ),
        migrations.AlterField(
            model_name='mapmonster',
            name='count',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='存在怪物的数量'),
        ),
    ]
